import type { ClientSession, Collection, Db, Filter } from 'mongodb';
import { ObjectId } from 'mongodb';
import {
  applicationIndexes,
  type ApplicationDocument,
  type ApplicationStatus,
} from './application.model.js';
import type { ApplicationDTO, ApplicationPage } from './dto.js';

export interface CreateApplicationData {
  // Pre-generated by the caller (see generateId) when the id must be known before the insert —
  // e.g. hiring's invitation-accept flow needs the application id for the escrow hold's
  // idempotency key and the contract's applicationId before the application row itself exists.
  // apply() lets Mongo assign one as usual.
  id?: string;
  listingId: string;
  clientAccountId: string;
  creativeAccountId: string;
  message?: string;
  // Defaults to 'pending' (the normal apply() flow). Invitation-accept passes 'accepted'
  // directly — see service.ts's acceptInvitation.
  status?: ApplicationStatus;
}

const APPLICATION_PROJECTION = {
  listingId: 1,
  clientAccountId: 1,
  creativeAccountId: 1,
  status: 1,
  message: 1,
  createdAt: 1,
  updatedAt: 1,
} as const;

function toDTO(doc: ApplicationDocument): ApplicationDTO {
  return {
    id: doc._id.toHexString(),
    listingId: doc.listingId.toHexString(),
    clientAccountId: doc.clientAccountId.toHexString(),
    creativeAccountId: doc.creativeAccountId.toHexString(),
    status: doc.status,
    message: doc.message,
    createdAt: doc.createdAt,
    updatedAt: doc.updatedAt,
  };
}

export class ApplicationRepository {
  private readonly collection: Collection<ApplicationDocument>;

  constructor(db: Db) {
    this.collection = db.collection<ApplicationDocument>('applications');
  }

  async createIndexes(): Promise<void> {
    for (const index of applicationIndexes) {
      await this.collection.createIndex(index.key, { name: index.name, unique: index.unique });
    }
  }

  // Lets a caller reserve an application id before the row exists — see CreateApplicationData.id.
  generateId(): string {
    return new ObjectId().toHexString();
  }

  async create(input: CreateApplicationData, session?: ClientSession): Promise<ApplicationDTO> {
    const now = new Date();
    const doc: ApplicationDocument = {
      _id: input.id ? new ObjectId(input.id) : new ObjectId(),
      listingId: new ObjectId(input.listingId),
      clientAccountId: new ObjectId(input.clientAccountId),
      creativeAccountId: new ObjectId(input.creativeAccountId),
      status: input.status ?? 'pending',
      message: input.message ?? null,
      createdAt: now,
      updatedAt: now,
    };
    await this.collection.insertOne(doc, session ? { session } : {});
    return toDTO(doc);
  }

  async findById(id: string): Promise<ApplicationDTO | null> {
    const doc = await this.collection.findOne(
      { _id: new ObjectId(id) },
      { projection: APPLICATION_PROJECTION },
    );
    return doc ? toDTO(doc) : null;
  }

  async findByListingAndCreative(
    listingId: string,
    creativeAccountId: string,
  ): Promise<ApplicationDTO | null> {
    const doc = await this.collection.findOne(
      { listingId: new ObjectId(listingId), creativeAccountId: new ObjectId(creativeAccountId) },
      { projection: APPLICATION_PROJECTION },
    );
    return doc ? toDTO(doc) : null;
  }

  async listByCreative(
    creativeAccountId: string,
    params: { limit: number; cursor?: string },
  ): Promise<ApplicationPage> {
    return this.listByFilter({ creativeAccountId: new ObjectId(creativeAccountId) }, params);
  }

  async listByListing(
    listingId: string,
    params: { limit: number; cursor?: string },
  ): Promise<ApplicationPage> {
    return this.listByFilter({ listingId: new ObjectId(listingId) }, params);
  }

  async updateStatus(
    id: string,
    status: ApplicationStatus,
    session?: ClientSession,
  ): Promise<ApplicationDTO | null> {
    const result = await this.collection.findOneAndUpdate(
      { _id: new ObjectId(id) },
      { $set: { status, updatedAt: new Date() } },
      {
        returnDocument: 'after',
        projection: APPLICATION_PROJECTION,
        ...(session ? { session } : {}),
      },
    );
    return result ? toDTO(result) : null;
  }

  // Talent-side stat tile: applications still awaiting a client decision.
  async countPendingForCreative(creativeAccountId: string): Promise<number> {
    return this.collection.countDocuments({
      creativeAccountId: new ObjectId(creativeAccountId),
      status: { $in: ['pending', 'interview_requested'] },
    });
  }

  // Employer-side stat tile: applications across all of the client's listings still awaiting a
  // decision. clientAccountId is denormalized onto the application at creation time (see the
  // model), so this doesn't need a cross-module join against listings.
  async countPendingForClient(clientAccountId: string): Promise<number> {
    return this.collection.countDocuments({
      clientAccountId: new ObjectId(clientAccountId),
      status: { $in: ['pending', 'interview_requested'] },
    });
  }

  // Reconciliation source of truth for listings' applicantCount cache: every application not
  // currently withdrawn, grouped by listing — matches exactly what the
  // application.created/application.withdrawn event handler increments/decrements. Exported via
  // index.ts as getApplicationCountsByListingIds.
  async countActiveByListingIds(listingIds: string[]): Promise<Record<string, number>> {
    if (listingIds.length === 0) {
      return {};
    }
    const rows = await this.collection
      .aggregate<{ _id: ObjectId; count: number }>([
        {
          $match: {
            listingId: { $in: listingIds.map((id) => new ObjectId(id)) },
            status: { $ne: 'withdrawn' },
          },
        },
        { $group: { _id: '$listingId', count: { $sum: 1 } } },
      ])
      .toArray();

    const counts: Record<string, number> = {};
    for (const row of rows) {
      counts[row._id.toHexString()] = row.count;
    }
    return counts;
  }

  private async listByFilter(
    baseFilter: Filter<ApplicationDocument>,
    { limit, cursor }: { limit: number; cursor?: string },
  ): Promise<ApplicationPage> {
    const filter: Filter<ApplicationDocument> = cursor
      ? { ...baseFilter, _id: { $lt: new ObjectId(cursor) } }
      : baseFilter;

    const docs = await this.collection
      .find(filter, { projection: APPLICATION_PROJECTION })
      .sort({ _id: -1 })
      .limit(limit + 1)
      .toArray();

    const hasMore = docs.length > limit;
    const items = docs.slice(0, limit).map(toDTO);
    const last = items[items.length - 1];
    return { items, nextCursor: hasMore && last ? last.id : null };
  }
}
